// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  BookReviewSidebar: [{type: 'autogenerated', dirName: 'books'}],
  MathSidebar: [{type: 'autogenerated', dirName: 'math'}],

  // BookReviewSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Trí Tuệ Tài Chính',
  //     items: [
  //       'books/Tri-Tue-Tai-Chinh/overview'
  //       ,'books/Tri-Tue-Tai-Chinh/chapter-1'
  //       ,'books/Tri-Tue-Tai-Chinh/chapter-2'
  //       ,'books/Tri-Tue-Tai-Chinh/chapter-3'
  //       ,'books/Tri-Tue-Tai-Chinh/chapter-4'
  //       ,'books/Tri-Tue-Tai-Chinh/chapter-5'
  //       ,'books/Tri-Tue-Tai-Chinh/chapter-6'
  //     ],
  //   },
  // ],
  // MathSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Caculus',
  //     items: [
  //       'books/Tri-Tue-Tai-Chinh/overview'
  //     ],
  //   },
  // ],
};

export default sidebars;
